# Generated by Django 3.2 on 2021-04-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Active_Leave_Entries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FacultyID', models.CharField(max_length=122)),
                ('application_date', models.DateField()),
                ('starting_date', models.DateField()),
                ('num_leaves', models.IntegerField()),
                ('curr_status', models.IntegerField()),
                ('desciption', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EntryID', models.IntegerField()),
                ('timecreated', models.DateField()),
                ('body', models.TextField()),
                ('FromFacultyID', models.CharField(max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('FacultyID', models.IntegerField(primary_key=True, serialize=False)),
                ('dept', models.CharField(max_length=8)),
                ('leaves_remaining', models.IntegerField()),
                ('permission_level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Previous_Cross_Cutting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FacultyID', models.IntegerField()),
                ('timebegin', models.DateTimeField()),
                ('timeend', models.DateTimeField()),
                ('permission_level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Previous_Record',
            fields=[
                ('EntryID', models.AutoField(primary_key=True, serialize=False)),
                ('ApplicantID', models.IntegerField()),
                ('DecisionMakerID', models.IntegerField()),
                ('starting_date', models.DateField()),
                ('num_leaves', models.IntegerField()),
                ('decisiondate', models.DateField()),
                ('was_approved', models.BooleanField()),
            ],
        ),
    ]
