# Generated by Django 3.2 on 2021-04-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decision_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EntryID', models.IntegerField()),
                ('timecreated', models.DateTimeField()),
                ('body', models.TextField(default='')),
                ('FromFacultyID', models.IntegerField()),
                ('DecisionMakerID', models.IntegerField()),
                ('verdict', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Previous_Request_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EntryID', models.IntegerField()),
                ('ApplicantID', models.IntegerField()),
                ('starting_date', models.DateField()),
                ('num_leaves', models.IntegerField()),
                ('was_approved', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='Previous_Record',
        ),
        migrations.AlterField(
            model_name='active_leave_entries',
            name='application_date',
            field=models.DateTimeField(),
        ),
    ]
