# Generated by Django 3.2 on 2021-04-17 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='active_leave_entries',
            old_name='desciption',
            new_name='description',
        ),
    ]
