# Generated by Django 3.2 on 2021-04-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_desciption_active_leave_entries_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='active_leave_entries',
            name='FacultyID',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='body',
            field=models.TextField(default=''),
        ),
    ]
