# Generated by Django 3.2 on 2021-04-20 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210420_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision_record',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
