# Generated by Django 3.2 on 2021-04-18 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210418_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='active_leave_entries',
            name='description',
        ),
    ]
