# Generated by Django 3.2 on 2021-04-20 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_decision_record_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decision_record',
            name='FromFacultyID',
        ),
    ]
