# Generated by Django 3.2 on 2021-04-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_active_leave_entries_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info_Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curr_year', models.IntegerField()),
                ('last_clean_date', models.DateField()),
            ],
        ),
    ]
