# Generated by Django 3.2 on 2021-04-17 15:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='activeleaveentries',
            fields=[
                ('entryid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('FacultyID', models.CharField(max_length=122)),
                ('application_date', models.DateField()),
                ('Starting_date', models.DateField()),
                ('No_of_leaves', models.IntegerField()),
                ('current_status', models.IntegerField()),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entryid', models.UUIDField()),
                ('body', models.TextField()),
                ('fromfacultyid', models.CharField(max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name='CrossCutting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.CharField(max_length=122)),
                ('FacultyID', models.CharField(max_length=122)),
                ('name', models.CharField(max_length=122)),
                ('Permission_level', models.IntegerField()),
                ('Designation', models.CharField(max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.CharField(max_length=122)),
                ('name', models.CharField(max_length=122)),
                ('dept', models.CharField(max_length=122)),
                ('leaves_remaining', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Previous_Cross_Cutting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FacultyID', models.CharField(max_length=122)),
                ('Timebegin', models.DateField()),
                ('Timeend', models.DateField()),
                ('Permission', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='www',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entryid', models.UUIDField()),
                ('FacultyID', models.CharField(max_length=122)),
            ],
        ),
    ]
